### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by shiftrtech** [scottlamb/retina#11]
Hey, I think this project is what I need to, I would like to chat with you about this, is there some discord server to talk or something similar?

Nice work.

**Comment by scottlamb** [comment]
Thank you. There's no discord server now. I'm traveling at the moment and not on a computer at a consistent time of day, so it might not be that helpful. I might try out a chat platform in a couple weeks.

**Comment by scottlamb** [comment]
We could try out github discussions now, though.
