### ISSUE TITLE
aac.rs miss a frequency arm "0x4 => 41_000,"

### ISSUE THREAD

**Issue by qianzhang5** [scottlamb/retina#22]
let sampling_frequency = match r
            .read_u8(4)
            .map_err(|e| format!("unable to read sampling_frequency: {}", e))?
        {
            0x0 => 96_000,
            0x1 => 88_200,
            0x2 => 64_000,
            0x3 => 48_000,
            0x4 => 41_000,  //<----- missing
            0x5 => 32_000,
            0x6 => 24_000,
            0x7 => 22_050,
            0x8 => 16_000,
            0x9 => 12_000,
            0xa => 11_025,
            0xb => 8_000,
            0xc => 7_350,

**Comment by scottlamb** [comment]
Thanks for catching this! I'll fix it when I get a chance later, unless you want to send a PR yourself.
