### ISSUE TITLE
Video file into specific time chunks (15/30/60 minutes)

### ISSUE THREAD

**Issue by nice-redbull** [scottlamb/retina#37]
Hi Scott, 

is it possible to split a video file into specific time chunks (15/30/60 minutes)?

**Comment by scottlamb** [comment]
As in #36: yes, it's possible, but I'm intending Retina to be "just" an RTSP library with some examples of how to use it, not a full equivalent of ffmpeg or the like.

Are you looking for a full-fledged NVR? Have you seen my [Moonfire NVR](https://github.com/scottlamb/moonfire-nvr) project?
