### ISSUE TITLE
 example: Fatal: Failed precondition: must SETUP before PLAY

### ISSUE THREAD

**Issue by lucaszanella** [scottlamb/retina#41]
```
root@39e12bac9e7a:/home/dev/external/retina# cargo run --example client mp4 --url rtsp://192.168.1.22:10554/udp/av0_0 --username admin --password 123456 out.mp4
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/examples/client mp4 --url 'rtsp://192.168.1.22:10554/udp/av0_0' --username admin --password 123456 out.mp4`
E20211128 20:55:52.260 main client] Fatal: Failed precondition: must SETUP before PLAY


```

**Comment by scottlamb** [comment]
The only reason I see that this would happen is if the example doesn't set up any video or audio streams:

*   It won't set up video if you pass `--no-video` or if the server doesn't offer any H.264 video streams (I haven't added H.265 support yet).
*   It won't set up audio if you pass `--no-audio` or if the server doesn't offer any AAC audio streams. (Only AAC can be placed into a `.mp4` file, and this simple example doesn't do any transcoding.)

I just pushed a commit which will better describe what streams it's setting up or ignoring and will produce a more helpful error message when it doesn't set up any streams. I marked it as fixing this issue, but please let me know if it doesn't explain what's happening and I'll reopen.
