### ISSUE TITLE
access raw RTCP packet (headers and all)

### ISSUE THREAD

**Issue by RustPanda** [scottlamb/retina#59]
Hello. To integrate `Gstreamer` and `WebRTC` into `Retina`, need to transfer the raw RTCP packet. Can you add `SenderReport::raw(&self) -> &[u8]`?
```rust
let launch = "rtpsession name=session \
    appsrc name=rtpsrc ! session.recv_rtp_sink \
    appsrc name=rtcpsrc ! session.recv_rtcp_sink \  
    session.recv_rtp_src ! rtph264depay ! h264parse ! vaapidecodebin ! autovideosink";
```

**Comment by scottlamb** [comment]
I can add something. RTCP comes in "compound packets" which usually start with a sender or receiver report (RFC 3550 says they MUST; RFC 5506 weakens this) and usually end with a source description (similarly, RFC 3550 says so, RFC 5506 says not necessarily). What does gstreamer expect—to get just sender report packets? to get compound packets? to get each packet within the compound packet individually?

**Comment by RustPanda** [comment]
@scottlamb

-compound packets can be sent to Gstreamer [GstRTCPBuffer](https://gstreamer.freedesktop.org/documentation/rtplib/gstrtcpbuffer.html?gi-language=c)
- I don't know if  sender report packets  will be enough for him [rtspsession](https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpsession.html?gi-language=c)

**Comment by scottlamb** [comment]
I'm working on an updated interface to access the full compound packet.

**Comment by scottlamb** [comment]
Now done, on the `next` branch. Please let me know how the new API works out for you.

**Comment by RustPanda** [comment]
@scottlamb thanks, I'll check this week
